// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccountsColumns holds the columns for the "accounts" table.
	AccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime", "postgres": "date"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime", "postgres": "date"}},
		{Name: "email", Type: field.TypeString, Default: ""},
		{Name: "email_password", Type: field.TypeString, Default: ""},
		{Name: "bind_email", Type: field.TypeString, Default: ""},
		{Name: "post_code", Type: field.TypeString, Default: ""},
		{Name: "password", Type: field.TypeString, Default: ""},
		{Name: "first_name", Type: field.TypeString, Default: ""},
		{Name: "last_name", Type: field.TypeString, Default: ""},
		{Name: "region", Type: field.TypeString, Default: ""},
		{Name: "ip", Type: field.TypeString, Default: ""},
		{Name: "window_name", Type: field.TypeString, Default: ""},
		{Name: "balance", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"mysql": "decimal(10,2)", "postgres": "numeric"}},
		{Name: "ip_used", Type: field.TypeBool, Default: false},
		{Name: "ref_url", Type: field.TypeString, Default: ""},
		{Name: "remark", Type: field.TypeString, Default: ""},
	}
	// AccountsTable holds the schema information for the "accounts" table.
	AccountsTable = &schema.Table{
		Name:       "accounts",
		Columns:    AccountsColumns,
		PrimaryKey: []*schema.Column{AccountsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountsTable,
	}
)

func init() {
}
