// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bb_bot/ent/account"
	"bb_bot/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountMixin := schema.Account{}.Mixin()
	accountMixinFields0 := accountMixin[0].Fields()
	_ = accountMixinFields0
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescCreatedAt is the schema descriptor for created_at field.
	accountDescCreatedAt := accountMixinFields0[0].Descriptor()
	// account.DefaultCreatedAt holds the default value on creation for the created_at field.
	account.DefaultCreatedAt = accountDescCreatedAt.Default.(func() time.Time)
	// accountDescUpdatedAt is the schema descriptor for updated_at field.
	accountDescUpdatedAt := accountMixinFields0[1].Descriptor()
	// account.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	account.DefaultUpdatedAt = accountDescUpdatedAt.Default.(func() time.Time)
	// account.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	account.UpdateDefaultUpdatedAt = accountDescUpdatedAt.UpdateDefault.(func() time.Time)
	// accountDescEmail is the schema descriptor for email field.
	accountDescEmail := accountFields[0].Descriptor()
	// account.DefaultEmail holds the default value on creation for the email field.
	account.DefaultEmail = accountDescEmail.Default.(string)
	// accountDescEmailPassword is the schema descriptor for emailPassword field.
	accountDescEmailPassword := accountFields[1].Descriptor()
	// account.DefaultEmailPassword holds the default value on creation for the emailPassword field.
	account.DefaultEmailPassword = accountDescEmailPassword.Default.(string)
	// accountDescBindEmail is the schema descriptor for bindEmail field.
	accountDescBindEmail := accountFields[2].Descriptor()
	// account.DefaultBindEmail holds the default value on creation for the bindEmail field.
	account.DefaultBindEmail = accountDescBindEmail.Default.(string)
	// accountDescPostCode is the schema descriptor for postCode field.
	accountDescPostCode := accountFields[3].Descriptor()
	// account.DefaultPostCode holds the default value on creation for the postCode field.
	account.DefaultPostCode = accountDescPostCode.Default.(string)
	// accountDescPassword is the schema descriptor for password field.
	accountDescPassword := accountFields[4].Descriptor()
	// account.DefaultPassword holds the default value on creation for the password field.
	account.DefaultPassword = accountDescPassword.Default.(string)
	// accountDescFirstName is the schema descriptor for firstName field.
	accountDescFirstName := accountFields[5].Descriptor()
	// account.DefaultFirstName holds the default value on creation for the firstName field.
	account.DefaultFirstName = accountDescFirstName.Default.(string)
	// accountDescLastName is the schema descriptor for lastName field.
	accountDescLastName := accountFields[6].Descriptor()
	// account.DefaultLastName holds the default value on creation for the lastName field.
	account.DefaultLastName = accountDescLastName.Default.(string)
	// accountDescRegion is the schema descriptor for region field.
	accountDescRegion := accountFields[7].Descriptor()
	// account.DefaultRegion holds the default value on creation for the region field.
	account.DefaultRegion = accountDescRegion.Default.(string)
	// accountDescIP is the schema descriptor for IP field.
	accountDescIP := accountFields[8].Descriptor()
	// account.DefaultIP holds the default value on creation for the IP field.
	account.DefaultIP = accountDescIP.Default.(string)
	// accountDescWindowName is the schema descriptor for windowName field.
	accountDescWindowName := accountFields[9].Descriptor()
	// account.DefaultWindowName holds the default value on creation for the windowName field.
	account.DefaultWindowName = accountDescWindowName.Default.(string)
	// accountDescBalance is the schema descriptor for balance field.
	accountDescBalance := accountFields[10].Descriptor()
	// account.DefaultBalance holds the default value on creation for the balance field.
	account.DefaultBalance = accountDescBalance.Default.(float64)
	// accountDescIPUsed is the schema descriptor for IPUsed field.
	accountDescIPUsed := accountFields[11].Descriptor()
	// account.DefaultIPUsed holds the default value on creation for the IPUsed field.
	account.DefaultIPUsed = accountDescIPUsed.Default.(bool)
	// accountDescRefURL is the schema descriptor for refURL field.
	accountDescRefURL := accountFields[12].Descriptor()
	// account.DefaultRefURL holds the default value on creation for the refURL field.
	account.DefaultRefURL = accountDescRefURL.Default.(string)
	// accountDescRemark is the schema descriptor for remark field.
	accountDescRemark := accountFields[13].Descriptor()
	// account.DefaultRemark holds the default value on creation for the remark field.
	account.DefaultRemark = accountDescRemark.Default.(string)
}
